name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python 3.14t
        run: uv python install 3.14.0+freethreaded

      - name: Sync environment
        run: uv sync

      - name: Ruff lint
        run: uv run ruff check

      - name: Ruff format check
        run: uv run ruff format --check
